### PR TITLE
turn on jmx metrics + JVM tuning

### PR DESCRIPTION
**Pull request by ankushgoyal**
JVM tuning is based on recommendations at http://docs.confluent.io/2.0.0/schema-registry/docs/deployment.html

TODO: pipe jmx metrics to datadog.

### CODE REVIEW

**Comment by ankushgoyal** [comment]
@nari-m - can we turn on jmx integration for the dd agents running on these instances ? - I think its simple config change - http://docs.datadoghq.com/integrations/java/ 

Or maybe we can try it together tomorrow.

**Comment by jontg** [comment]
You should be able to just send a PR against [the relevant chef code](https://github.com/relateiq/chef/blob/378879be4414e6318c4fa48b16db6bcb8616d54b/cookbooks/voldemort/templates/default/jmx.yaml.erb) @ankushgoyal if you have specific metrics you want.  We already have this for a number of our other java-based machines.

**Comment by jontg** [comment]
@ankushgoyal where do environment variables like `SCHEMA_REGISTRY_JVM_PERFORMANCE_OPTS ` get used?

**Comment by ankushgoyal** [comment]
@jontg this is the script to run schema registry server (that expects env. variables) - https://github.com/confluentinc/schema-registry/blob/2.x/bin/schema-registry-run-class#L71

**Pull request merged**
